auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:tekton/pipeline_controller
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:tekton/pipeline_entrypoint
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:tekton/pipeline_nop
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:tekton/pipeline_sidecarlogresults
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:tekton/pipeline_workingdirinit
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:tekton/pipeline_events
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:tekton/pipeline_resolvers
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:tekton/pipeline_webhook
