auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.48.0@sha256:c2442a0f832ce36afd1b2a7a2d971a30be4aae92ebc384c8ee24f073688bc61e: txowner/pipeline_controller
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypointv:v0.48.0@sha256:6ea5a0dd712b1c2204473fbf809432c31df8f062135f84c6ccf02d37cdfd9e76: txowner/pipeline_entrypoint
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.48.0@sha256:3fdf8f51abaaf2b2cb3f583545c83204c7948f44d5bc3badffb322355e42caaa: txowner/pipeline_nop
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.48.0@sha256:1bb043c7f27598de1e5a632b54ccff45a05aac420005298f3b50c4ec4cbf1f96: txowner/pipeline_sidecarlogresults
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.48.0@sha256:4b2917f4c4a429a10c2828b6ff8eb8e94ffa8eb321375294632c1467cf2de61d: txowner/pipeline_workingdirinit
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.48.0@sha256:04e81d0051a3dd4adbdaa4214148a007b7c197db7ef801bb974e83c757007335: txowner/pipeline_events
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.48.0@sha256:10cebbc9a9177527cfb60539ce7db217d7dbc4e8ead2ef59e20c41b4085e8769: txowner/pipeline_resolvers
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.48.0@sha256:f3b7b6681e67dad5b28d29da48a78b0d77b84cad58d9ff1e3a1355e1a5c9f528: txowner/pipeline_webhook

