auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.48.0: txowner/pipeline_controller
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypointv:v0.48.0: txowner/pipeline_entrypoint
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.48.0: txowner/pipeline_nop
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.48.0: txowner/pipeline_sidecarlogresults
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.48.0: txowner/pipeline_workingdirinit
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.48.0: txowner/pipeline_events
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.48.0: txowner/pipeline_resolvers
    gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.48.0: txowner/pipeline_webhook
